spring:
  application:
    name: web
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web01
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

logging:
  level:
    com.yep.web.mapper: debug
    org.apache.ibatis: debug
    java.sql: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    java.sql.ResultSet: debug
    org.springframework.jdbc.support.JdbcTransactionManager: debug

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n'

aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucket-name: java-itheima-yep
    region: cn-guangzhou